services:
  postgres-database:
    image: postgres:17
    container_name: measure-postgres-database
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: measure
      POSTGRES_PASSWORD: measure
      POSTGRES_DB: measure
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
